CatoTH/antragsgruen

- web/js/antragsgruen.js
In diesem Stream sammle ich kleine Änderungen, die keinen eigenen Branch lohnen und nicht eilig sind; ich mache dann jeweils einen Pull Request, in dem sich die Änderungen sammeln, und Du kannst ihn durchgehen und übernehmen, wenn Du dazu kommst. Macht das Sinn?
> Kleine Änderungen

- views/admin/motion/list_all.php
Ich hab einfach den `<span>` nachgemacht, der bei den eigenständigen Anträgen um den Link rum ist -- hab nicht nachvollzogen, warum das einen Unterschied macht; Hauptsache es funktioniert :-)
> Änderungsantragstitel wurden in der Admin-Ansicht nicht eingerückt

- components/mail/SMTP.php
> label bug fix for missconfigured SMTP

- models/sectionTypes/TextHTML.php
- models/sectionTypes/TextSimple.php
make it possible to view crossed text within the PDFs, not only the web view
> crossed text within the PDFs

- views/pdfLayouts/DBJR.php
– enable multilign motion type
– improve PdfLogo: only with is fix, all other dimensions are calculated
> improve DBJR PDF Template

- config/config.template.json
- config/config.template_singlesite.json
- config/config_tests.template.json
- models/sectionTypes/PDF.php
- models/settings/AntragsgruenApp.php
- views/pdfLayouts/BDKPDF.php
- views/pdfLayouts/ByLDKPDF.php
- views/pdfLayouts/DBJRPDF.php
The BugFix from https://github.com/CatoTH/antragsgruen/pull/201 is included in this pull request, too.
With new settings in config.json, one can now include PDF-files into the export-layout.
> BugFix + new inclusion type

- assets/db/create.sql
> fix foreign key constraint violations for comment replies

- views/consultation/sidebar.php
> no sidebar link to PDF collection for motion type without PDF layout

- views/amendment/edit_form.php
- views/motion/edit_form.php
A feature that was requested for our DiB instance of antragsgrün and that might also be useful for others -- back buttons on the pages for motions and amendments, leading back to the main page and the motion page, respectively.
> back buttons

- package.json
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#private
> Prevent accidental publishing by npm

- models/layoutHooks/StdHooks.php
thanks to https://validator.w3.org/
> Fix invalid html: change end tag

- .github/workflows/node-checks.yml
- package.json
Just a basic `will it build` test with latest lts node.
> Add GH action for node test build

- .github/workflows/php-checks.yml
Just a basic test with composer for every supported PHP version.
> Add GH action to php verify composer

- web/index.php
Smash the tiny typo before it escapes...
> Fix tiny typo

- .github/dependabot.yml
Let the bot do the chore of checking for updates.
> Add dependabot to autoreview and PR GH action updates

- package-lock.json
- package.json
- web/typescript/frontend/MotionMergeAmendments.ts
Builds with one necessary type definition.
Disclaimer: I did not test the front-end.
>  Update typescript from 3 to 4 

- package-lock.json
- package.json
> Update to typescript 5

- components/UrlHelper.php
- components/diff/amendmentMerger/ParagraphMerger.php
- components/yii/UrlManager.php
- controllers/admin/MotionTypeController.php
- models/votings/VotingItemGroup.php
- plugins/antragsgruen_sites/Module.php
- plugins/frauenrat/controllers/MotionController.php
- plugins/gruene_de_saml/SamlLogin.php
- web/index.php
> Migrate to `str_starts_with`

- plugins/gruene_de_saml/SamlLogin.php
- views/manager/siteconfig.php
- views/merging/_public_version_content.php
- web/index-production.php
> chore(php): migrate to null coalescing operator

- components/diff/Diff.php
- components/diff/Engine.php
- components/diff/MovingParagraphDetector.php
- components/diff/amendmentMerger/ParagraphMerger.php
- components/mail/Base.php
- config/web.php
- docs/create-update.php
- models/forms/AntragsgruenInitDb.php
- models/votings/VotingItemGroup.php
- plugins/frauenrat/LayoutHooks.php
- plugins/frauenrat/pdf/Frauenrat.php
- plugins/green_manager/views/manager/wizard_subdomain.php
- plugins/member_petitions/views/_motion_sorter.php
- views/createsiteWizard/sitedata_subdomain.php
Replace strpos() calls with str_starts_with() or str_contains() if possible.
Makes code better readable.
> chore(php): modernize strpos

- package.json
Outdated since Typescript@v2
https://github.com/typings/typings
> fix: remove outdated npm script

- .github/workflows/node-checks.yml
- package-lock.json
- package.json
* add eslint check to GH Action
* update eslint & typescript
> feat: add eslint check to GH Action

- commands/UserController.php
- components/diff/AffectedLinesFilter.php
- components/diff/DiffRenderer.php
- components/mail/Base.php
- models/db/Amendment.php
- models/db/User.php
- models/settings/Layout.php
> chore: migrate to `str_contains`

- controllers/InstallationController.php
> fix: use constant `PHP_VERSION`

- .github/workflows/node-checks.yml
- package-lock.json
- package.json
* [breaking] require min node 20
* update build dependencies
> chore(npm): require min node 20

- web/typescript/backend/ResponsibilitySetter.ts
- web/typescript/frontend/LineNumberHighlighting.ts
> fix(JS): migrate deprecated functions

- eslint.config.mjs
- package-lock.json
- package.json
- web/typescript/frontend/AmendmentShow.ts
- web/typescript/frontend/EditorialEdit.ts
- web/typescript/frontend/MotionShow.ts
> feat(eslint): check for indirect browser global variable usage 
