CatoTH/antragsgruen

protected/models/Aenderungsantrag.php, protected/models/VeranstaltungsEinstellungen.php, protected/views/admin/veranstaltungen/update.php
Setzt #46 um. Zeilennummern können links mit Nullen gepadded werden;
statt „Ä“ kann ein beliebiges (ggf. leeres) Präfix für Änderungsanträge angegeben
werden.
=> flexiblere Antragsnummerierung

protected/models/Aenderungsantrag.php, protected/views/antrag/anzeige.php
resolves #43
In der Antragsanzeige werden sowohl rechts am Rand als auch unter dem Antrag zusätzlich zu den Antragskürzeln auch die ÄnderungsantragstellerInnen (mit Gliederung) angezeigt. Bei mir sieht das so aus:
=> ÄnderungsantragstellerInnen anzeigen

protected/models/Aenderungsantrag.php, protected/models/VeranstaltungsEinstellungen.php, protected/views/admin/veranstaltungen/update.php, protected/views/aenderungsantrag/bearbeiten_form.php
Auch bei Nummerierung nach Zeilennummern können jetzt mehrere Absätze in einem Änderungsantrag geändert werden. Der Code für die Beschränkung ist noch da und kann über die Variable `VeranstaltungsEinstellungen.ae_nur_ein_absatz` wieder aktiviert werden, die vorerst immer `false` ist.
Die Commits sind unnötig chaotisch; die tatsächlichen Änderungen sind gering.
=> Beschränkung auf einen Absatz aufheben

models/db/Amendment.php, models/db/Motion.php
Beim Nachvollziehen dieses Bugs fiel mir auf, daß die Antragsteller*innen anscheinend dreimal ausgelesen werden, wenn ein Antrags-PDF erzeugt wird -- einmal an der hier geänderten Stelle, aber davor schon zweimal, einmal in views/motion/pdf_tex.php (`$layout->author  = $motion->getInitiatorsStr()`) und einmal in views/motion/LayoutHelper::renderTeX (`$initiators` wird mit `$motion->getInitiators ()` gefüllt) (bzw. in den entsprechenden Dateien in views/amendment). Diese Antragsteller*innen werden aber anscheinend gar nicht verwendet. Ich überblicke nicht, wofür dieser Code sonst noch verwendet wird, aber vielleicht könnte man diese Abfragen einsparen.
=> Organisationen fehlten als Antragstellerinnen in PDFs

controllers/AmendmentController.php, controllers/MotionController.php
Wenn man einen Änderungsantrag schreibt und dann "korrigiert", wurde trotzdem das vorherige Diff aus dem Cache angezeigt. Bei eigenständigen Anträgen hab ich keine konkreten Auswirkungen gesehen, hab aber da auch einen cache flush eingefügt, weil auch da vermutlich der Cache beim Edit ungültig wird.
=> flush cache on edit

components/diff/Diff.php
In `components\diff\Diff::groupOperations` werden list items gesondert behandelt, aber wenn nach dem Ende der Liste weitere Elemente ebenfalls gelöscht oder ebenfalls eingefügt werden, wurden die an den letzten list item rangehängt, mit der Folge, dass dann in `components\diff\Diff::wrapWithDelete` das Ganze als list item behandelt wurde und einfach nur `class="delete"` reingesetzt wurde, anstatt es in `<del></del>` einzuschließen. Ich hab es so geändert, dass das Akkumulieren der Gruppe nicht nur beendet wird, wenn ein list item kommt, sondern auch wenn ein list item voranging.
=> deletion beyond list was being dropped

components/latex/Exporter.php, config/urls.php, controllers/admin/AmendmentController.php, controllers/admin/MotionController.php, messages/de/admin.php, messages/en/admin.php, views/admin/amendment/pdf_zip_list.php, views/admin/index/index.php, views/admin/motion/pdf_zip_list.php, views/amendment/pdf_tex.php, views/motion/pdf_tex.php
Ich hab die Erstellung von PDFs aus `views/{motion|amendment}/pdf_tex.php` abstrahiert, um sie auch wo anders verwenden zu können -- bin nicht sicher, ob Exporter dafür der beste Ort war, sonst kannst Du's vielleicht noch wo anders hinschieben.
=> ZIP-Archiv der PDFs aller Anträge bzw. Änderungsanträge

composer.json, models/VarStream.php, models/sectionTypes/ISectionType.php, models/sectionTypes/Image.php, models/sectionTypes/PDF.php, models/sectionTypes/TabularData.php, models/sectionTypes/TextHTML.php, models/sectionTypes/TextSimple.php, models/sectionTypes/Title.php, views/motion/pdf_tcpdf.php, views/pdfLayouts/BDK.php, views/pdfLayouts/BDKPDF.php, views/pdfLayouts/ByLDKPDF.php, views/pdfLayouts/DBJRPDF.php
Since TCPDF doesn't support the inclusion of other PDF-Files as template and other inclusion times innately, FPDI has been added via composer. FPDI extends TCPDF so everywhere, TCPDF was used, now FPDI has to be used.
PDF attachments are included within the pdf-export now.
=> pdf export: include pdf attachments

config/common.php
Strangely, `date_default_timezone_set` doesn't set the default timezone properly in our setting (Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64), PHP 7.0.33-0ubuntu0.16.04.4 (cli) (NTS)). If you call it with `Europe/Berlin` and then immeditely call `date_default_timezone_get`, it still returns `UTC`. Instead, `ini_set('date.timezone', $timezone)` works. I added it, instead of replacing the call to `date_default_timezone_set`, since I don't know whether this works in other settings.
=> set default time zone

models/settings/Layout.php
The JS files for the specific language are minified via gulp but not served in the minified version.
=> Serve minified language JS

README.md
Current version can be found in the package.json
=> Doc: remove explicit vue version

package.json
Gives developers a hint which nodejs version works.
Tested with current nodejs 16.
* https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines
* #624
=> Add supported nodejs to package.json

components/UrlHelper.php
This change fixes a bug when the app is running on "http" and is deployed behind a reverse proxy running on "https" 
It fails in the url comparison since the https != http which is used in $_SERVER['REQUEST_SCHEME'].
$_SERVER['HTTP_X_FORWARDED_PROTO']  takes precedent over  $_SERVER['REQUEST_SCHEME']
=> Allow reverse proxies

.github/dependabot.yml
News:
https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/
Result:
Just one PR instead of one PR per updated dependency.
=> Grouped dependabot pull requests

models/forms/AntragsgruenInitSite.php, plugins/discourse/Tools.php
`rand` has randomness / security flaws. It is recommended to use `random_int`.
=> chore(php): migrate to `random_int`

models/db/Consultation.php, models/sectionTypes/ISectionType.php, models/settings/InitiatorForm.php, models/settings/Stylesheet.php, models/settings/VotingData.php, models/supportTypes/SupportBase.php, models/votings/VotingItemGroup.php, plugins/drupal_civicrm/DrupalPasswordHashing.php, plugins/egp/LayoutHooks.php, tests/Support/Helper/ConfigurationChanger.php
Visibility MUST be declared on all properties and methods; abstract and final MUST be declared before the visibility; static MUST be declared after the visibility.
Source: https://cs.symfony.com/doc/rules/class_notation/visibility_required.html
=> fix(php): visibility required

package-lock.json, package.json
Seems not directly used. May be an old (optional peer) dependency.
=> Remove unused npm `cloneable-readable`

gulpfile.js, package-lock.json, package.json
Library not maintained anymore:
https://github.com/andyearnshaw/Intl.js/issues/341 
Modern browsers do support intl out of the box.
=> fix: remove outdated browser polyfill for intl

eslint.config.mjs, web/typescript/backend/AdminIndex.ts, web/typescript/backend/MemberPetitionRespond.ts, web/typescript/backend/ProposedProcedureExport.ts, web/typescript/backend/ProposedProcedureOverview.ts, web/typescript/backend/UserList.ts, web/typescript/frontend/AccountEdit.ts, web/typescript/frontend/CopyUrlToClipboard.ts, web/typescript/frontend/DeadlineDebugBar.ts, web/typescript/frontend/InitiatorForm.ts, web/typescript/frontend/LineNumberHighlighting.ts, web/typescript/frontend/MergeInit.ts, web/typescript/frontend/MergeSingleAmendment.ts, web/typescript/frontend/MotionMergeAmendmentsPublic.ts, web/typescript/frontend/UserNotificationsForm.ts, web/typescript/shared/AmendmentEditSinglePara.ts
=> fix(jQuery): migrate deprecated jQuery functions

views/consultation/sidebar.php
Currently the small (mobile) sidebar will say the `pdf_motions` text twice which is quite confusing as the first is the resolutions:
But the non-small sidebar talks about the resolutions:
The fix just re-uses the `pdf_resolutions` key which should make it look something like this:
=> Fix that small sidebar would not say resolutions for PDFs

components/mail/SMTP.php
`declare(strict_types=1);`
Introduced here
https://github.com/CatoTH/antragsgruen/commit/349522e7996c46ccb9007ac00c191b29aee8df7b#diff-5bd33395e5715c82071cef80cbfbb57ff327fd27e99c62c6d39da556d83c074bR3
This change makes no authentication throw, an exception
We use IP based auth and don't; need username and password. 
`urlencode` expects a string. Before strict_types it was ok to pass null now it throws.
=> Prevent urlencode throw an exception
